### ISSUE TITLE
Hello! license question

### ISSUE THREAD

**Issue by citizen88** [ShinoNoNuma/Json-Text-Difference#1]
Hello,

I really like your plugin!
I would like to use it but I noticed that you haven't added a license to the project.
This means according to Github that it can't be used by others without an explicit permission from the author.
Would you consider in order for others to be able to use it to add a license such as MIT ?
This seems to be the most popular with .js

Thank you!

**Comment by ShinoNoNuma** [comment]
Hey @citizen88, 
I've added the license. 
Please feel free to use it, with a clear conscience.
